name: PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  pull-requests: write

jobs:
  comment-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Comment preview link
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 Preview ready for commit `${{ github.event.pull_request.head.sha }}`
            🔗 **Preview URL:** https://rawcdn.githack.com/${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.sha }}/index.html
            _Served via raw.githack.com_
          body-includes: 'Preview URL:'
